/**
 * Every icon in the app comes from lucide-react, re-exported here under
 * app-meaning names so a swap only ever happens in one file.
 */
export {
  Activity as ActivityIcon,
  ArrowRight as ArrowRightIcon,
  Award as MilestoneIcon,
  Bot as AssistantIcon,
  Brain as SkillIcon,
  Check as CheckIcon,
  ChevronDown as ChevronDownIcon,
  ChevronLeft as CollapseIcon,
  ChevronRight as ExpandIcon,
  ChevronUp as ChevronUpIcon,
  CircleAlert as AlertIcon,
  CircleCheck as CircleCheckIcon,
  CircleDashed as CirclePendingIcon,
  Compass as RoadmapIcon,
  Download as DownloadIcon,
  Flame as StreakIcon,
  Globe as WebsiteIcon,
  GraduationCap as BrandIcon,
  Hammer as ProjectIcon,
  KeyRound as PasswordIcon,
  LayoutDashboard as DashboardIcon,
  Loader as LoaderIcon,
  LogOut as LogOutIcon,
  MapPin as PinIcon,
  Menu as MenuIcon,
  MessageSquare as ChatIcon,
  Moon as MoonIcon,
  Pencil as EditIcon,
  Play as PlayIcon,
  Plus as PlusIcon,
  RotateCcw as ReopenIcon,
  Send as SendIcon,
  Share as ShareIcon,
  Sparkles as SparklesIcon,
  Star as StarIcon,
  Sun as SunIcon,
  Target as GoalIcon,
  Trash2 as TrashIcon,
  TrendingUp as TrendingUpIcon,
  User as ProfileIcon,
  Video as VideoIcon,
  X as CloseIcon,
  Archive as ArchiveIcon,
  ArchiveRestore as UnarchiveIcon,
  CalendarDays as CalendarIcon,
  BookOpen as BookIcon,
  Briefcase as BriefcaseIcon,
  ListChecks as StagesIcon,
  Clock as ClockIcon,
} from 'lucide-react';
